/**
 * @method/mcp — Model A (deploy-time manifest) yaml generator (PRD-066 §7.7).
 *
 * Helper used at deploy time by tenant-app maintainers to hand-curate
 * `cortex-app.yaml spec.tools[]` from a methodology's Hoare tool set.
 *
 * **Pure.** No IO. Returns a `{ toolsYaml: string }` fragment the
 * operator pastes under `spec.tools`. Does not read or write files.
 *
 * Shape of the emitted block (RFC-005 §3, S9 §4):
 *   spec:
 *     tools:
 *       - name: method.<methodologyId>.<toolId>
 *         operation: method.<methodologyId>.<toolId>
 *         displayName: ...
 *         description: ...
 *         inputSchema: { ... }        # inline JSON literal
 *     operations:
 *       - name: method.<methodologyId>.<toolId>
 *         description: ...
 *         transport: mcp-tool
 *         write: true|false
 *
 * This is the v1 fallback until Track B unblocks (CORTEX-Q1/Q2).
 */

import type { Tool } from "@method/methodts";
import { methodtsToCortex } from "./cortex-mapping.js";
import type { ToolRegistrationPayload } from "./types.js";

export interface GenerateStaticToolsSectionInput {
  readonly methodologyId: string;
  readonly tools: ReadonlyArray<Tool<unknown>>;
  readonly roleAuthorizations?: ReadonlyArray<{
    readonly roleId: string;
    readonly authorizedToolIds: ReadonlyArray<string>;
  }>;
  readonly schemas?: ReadonlyArray<{
    readonly toolId: string;
    readonly inputSchema?: Readonly<Record<string, unknown>>;
    readonly outputSchema?: Readonly<Record<string, unknown>>;
  }>;
}

export interface ToolsYaml {
  /** A ready-to-paste `spec` fragment — string form. */
  readonly yaml: string;
  /** The structured payload (useful for tests and for programmatic wiring). */
  readonly payload: ToolRegistrationPayload;
}

/**
 * Generate the `cortex-app.yaml spec.tools[] / spec.operations[]` block
 * for Model A (deploy-time manifest). The caller pastes the yaml into
 * their tenant app manifest, commits, and redeploys.
 *
 * **Pure.** Hand-written YAML emitter (no js-yaml dep) — keeps
 * @method/mcp transitive-dep-free. Format is deterministic.
 */
export function generateStaticToolsSection(
  input: GenerateStaticToolsSectionInput,
): ToolsYaml {
  const payload = methodtsToCortex({
    methodologyId: input.methodologyId,
    tools: input.tools,
    roleAuthorizations: input.roleAuthorizations ?? [],
    schemas: input.schemas,
  });

  const lines: string[] = [];
  lines.push("spec:");
  lines.push("  # Generated by @method/mcp generateStaticToolsSection — PRD-066 Model A.");
  lines.push(`  # Methodology: ${input.methodologyId}`);
  lines.push("  operations:");
  for (const op of payload.operations) {
    lines.push(`    - name: ${yamlString(op.name)}`);
    lines.push(`      description: ${yamlString(op.description)}`);
    lines.push(`      transport: ${op.transport}`);
    lines.push(`      write: ${op.write === true ? "true" : "false"}`);
    if (op.scope) {
      lines.push(`      scope:`);
      lines.push(
        `        methodologyId: ${yamlString(op.scope.methodologyId)}`,
      );
    }
  }
  lines.push("  tools:");
  for (const t of payload.tools) {
    lines.push(`    - name: ${yamlString(t.name)}`);
    lines.push(`      operation: ${yamlString(t.operation)}`);
    if (t.displayName !== undefined) {
      lines.push(`      displayName: ${yamlString(t.displayName)}`);
    }
    lines.push(`      description: ${yamlString(t.description)}`);
    lines.push(`      inputSchema: ${jsonInline(t.inputSchema)}`);
    if (t.outputSchema) {
      lines.push(`      outputSchema: ${jsonInline(t.outputSchema)}`);
    }
  }
  if (payload.suggestedPolicy && payload.suggestedPolicy.length > 0) {
    lines.push("  # Suggested Layer-2 default_policy — admin-owned, publish separately.");
    lines.push("  suggestedPolicy:");
    for (const entry of payload.suggestedPolicy) {
      lines.push(`    - role: ${yamlString(entry.role)}`);
      lines.push(`      operations:`);
      for (const opName of entry.operations) {
        lines.push(`        - ${yamlString(opName)}`);
      }
    }
  }

  return { yaml: lines.join("\n") + "\n", payload };
}

// ── tiny yaml-safe emitters ──────────────────────────────────────────────────

function yamlString(s: string): string {
  // Double-quote unless safe bare. We always quote for determinism + safety.
  return JSON.stringify(s);
}

function jsonInline(obj: Readonly<Record<string, unknown>>): string {
  // YAML accepts inline JSON (flow scalars/mappings). Deterministic
  // key ordering — sort by key at the top level for reproducibility.
  const sorted: Record<string, unknown> = {};
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = obj[key];
  }
  return JSON.stringify(sorted);
}
