// ── PRD 014: Pre-Commit Hook Generator ─────────────────────────
// Generates a bash pre-commit hook that enforces allowed_paths
// scope constraints in git worktrees. The hook is self-contained
// with zero runtime dependencies.

import { writeFileSync, mkdirSync, chmodSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

/**
 * Scope enforcement configuration for a session.
 */
export interface ScopeConstraint {
  /** Glob patterns of files the agent is allowed to modify. */
  allowed_paths: string[];
  /**
   * Enforcement mode:
   * - 'enforce': pre-commit hook rejects out-of-scope commits (default)
   * - 'warn': PTY watcher emits events but commits are not blocked
   */
  mode: 'enforce' | 'warn';
}

/**
 * Generate the bash pre-commit hook script content.
 *
 * Uses bash pattern matching to check staged files against allowed patterns.
 * The hook is designed to work with Git for Windows bash and standard Unix bash.
 *
 * @param sessionId - Session identifier for traceability in hook comments
 * @param allowedPaths - Array of glob patterns the agent may modify
 * @returns The complete bash hook script as a string
 */
export function generateHookScript(sessionId: string, allowedPaths: string[]): string {
  if (allowedPaths.length === 0) {
    // No constraint — hook is a no-op
    return '#!/usr/bin/env bash\n# PRD 014: No scope constraints — all paths allowed\nexit 0\n';
  }

  // Convert glob patterns to bash-compatible patterns.
  // gitignore-style '**' maps to bash extglob '**' (with shopt -s globstar).
  // For pattern matching via [[ $file == $pattern ]], bash handles * and ** natively.
  const escapedPatterns = allowedPaths.map(p => {
    // Escape single quotes in patterns for safe bash embedding
    return p.replace(/'/g, "'\\''");
  });

  const patternsArray = escapedPatterns.map(p => `'${p}'`).join(' ');
  const patternsComment = allowedPaths.map(p => `#   ${p}`).join('\n');

  return `#!/usr/bin/env bash
# Auto-generated by pv-method bridge (PRD 014)
# Scope enforcement for session: ${sessionId}
# Allowed paths:
${patternsComment}

ALLOWED_PATTERNS=(${patternsArray})

# Convert a glob pattern to a bash regex where:
#   ** matches any characters (including /)
#   *  matches any characters except /
#   ?  matches any single character except /
#   .  is escaped to literal dot
glob_to_regex() {
  local pattern="$1"
  local regex=""
  local i=0
  local len=\${#pattern}
  while [ $i -lt $len ]; do
    local char="\${pattern:$i:1}"
    local next="\${pattern:$((i+1)):1}"
    if [ "$char" = "*" ] && [ "$next" = "*" ]; then
      local after="\${pattern:$((i+2)):1}"
      if [ "$after" = "/" ]; then
        regex+="(.+/)?"; i=$((i+3))
      else
        regex+=".*"; i=$((i+2))
      fi
    elif [ "$char" = "*" ]; then
      regex+="[^/]*"; i=$((i+1))
    elif [ "$char" = "?" ]; then
      regex+="[^/]"; i=$((i+1))
    elif [ "$char" = "." ]; then
      regex+="[.]"; i=$((i+1))
    else
      regex+="$char"; i=$((i+1))
    fi
  done
  echo "$regex"
}

# Get staged files
STAGED=$(git diff --cached --name-only)

if [ -z "$STAGED" ]; then
  exit 0
fi

VIOLATIONS=()

while IFS= read -r file; do
  [ -z "$file" ] && continue
  # Strip trailing CR (Windows CRLF)
  file="\${file%$'\\r'}"
  allowed=false
  for pattern in "\${ALLOWED_PATTERNS[@]}"; do
    # If pattern has no /, allow matching at any depth (gitignore semantics)
    if [[ "$pattern" != */* ]]; then
      pattern="**/$pattern"
    fi
    regex=$(glob_to_regex "$pattern")
    if [[ "$file" =~ ^$regex$ ]]; then
      allowed=true
      break
    fi
  done
  if [ "$allowed" = false ]; then
    VIOLATIONS+=("$file")
  fi
done <<< "$STAGED"

if [ \${#VIOLATIONS[@]} -gt 0 ]; then
  echo ""
  echo "SCOPE VIOLATION: The following files are not in allowed_paths for this session:"
  printf '  %s\\n' "\${VIOLATIONS[@]}"
  echo "Allowed patterns: \${ALLOWED_PATTERNS[*]}"
  echo ""
  echo "Remove the file(s) from staging (git reset HEAD '<file>') or request scope extension."
  echo "Session: ${sessionId}"
  exit 1
fi

exit 0
`;
}

/**
 * Resolve the correct hooks directory for a git worktree.
 *
 * For linked worktrees, the hooks path may differ from the main repository.
 * Uses `git rev-parse --git-path hooks` to resolve correctly across git versions.
 *
 * @param worktreePath - The root path of the worktree
 * @returns Absolute path to the hooks directory
 */
export function resolveHooksDir(worktreePath: string): string {
  try {
    const hooksPath = execSync('git rev-parse --git-path hooks', {
      cwd: worktreePath,
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();

    // git rev-parse may return a relative path — resolve it
    if (hooksPath.startsWith('/') || /^[A-Z]:/i.test(hooksPath)) {
      return hooksPath;
    }
    return join(worktreePath, hooksPath);
  } catch {
    // Fallback: standard .git/hooks location
    return join(worktreePath, '.git', 'hooks');
  }
}

/**
 * Install a scope-enforcing pre-commit hook in a worktree.
 *
 * Creates the hooks directory if it doesn't exist, writes the hook script,
 * and sets executable permissions. Only operates on worktree-isolated sessions.
 *
 * @param worktreePath - Path to the worktree root
 * @param sessionId - Session identifier for hook traceability
 * @param allowedPaths - Glob patterns of files the agent may modify
 * @returns Object indicating success and the hook file path
 */
export function installScopeHook(
  worktreePath: string,
  sessionId: string,
  allowedPaths: string[],
): { installed: boolean; hookPath: string | null; error?: string } {
  if (allowedPaths.length === 0) {
    return { installed: false, hookPath: null };
  }

  try {
    const hooksDir = resolveHooksDir(worktreePath);
    const hookPath = join(hooksDir, 'pre-commit');

    // Ensure hooks directory exists
    mkdirSync(hooksDir, { recursive: true });

    // Check for existing pre-commit hook (F-D-3: don't silently overwrite)
    if (existsSync(hookPath)) {
      const existing = readFileSync(hookPath, 'utf-8');
      if (!existing.includes('PRD 014')) {
        // Chain: prepend scope check, then call existing hook
        const script = generateHookScript(sessionId, allowedPaths);
        const chained = script.replace(
          /^exit 0\n$/m,
          '# Chain: run original pre-commit hook\nexec "$(dirname "$0")/pre-commit.original" "$@" 2>/dev/null\nexit 0\n',
        );
        writeFileSync(hookPath + '.original', existing, { encoding: 'utf-8' });
        try { chmodSync(hookPath + '.original', 0o755); } catch { /* Windows */ }
        writeFileSync(hookPath, chained, { encoding: 'utf-8' });
        try { chmodSync(hookPath, 0o755); } catch { /* Windows */ }
        return { installed: true, hookPath };
      }
    }

    // Generate and write the hook script
    const script = generateHookScript(sessionId, allowedPaths);
    writeFileSync(hookPath, script, { encoding: 'utf-8' });

    // Make executable (Unix). On Windows, git uses bash to run hooks,
    // so the shebang line is sufficient, but we set permissions anyway.
    try {
      chmodSync(hookPath, 0o755);
    } catch {
      // chmod may fail on Windows — non-fatal, hooks still work via bash
    }

    return { installed: true, hookPath };
  } catch (e) {
    return {
      installed: false,
      hookPath: null,
      error: `Failed to install scope hook: ${(e as Error).message}`,
    };
  }
}

/**
 * Check if a file path matches any of the allowed patterns.
 *
 * This is the TypeScript equivalent of the bash pattern matching in the hook.
 * Used by the PTY watcher for real-time scope violation detection (Phase 2).
 *
 * @param filePath - The file path to check (relative to repo root)
 * @param allowedPaths - Array of glob patterns
 * @returns true if the file matches at least one allowed pattern
 */
export function isPathAllowed(filePath: string, allowedPaths: string[]): boolean {
  if (allowedPaths.length === 0) return true; // No constraint

  // Normalize path separators and resolve traversal
  const normalized = normalizePath(filePath);

  for (const pattern of allowedPaths) {
    if (matchGlobPattern(normalized, pattern.replace(/\\/g, '/'))) {
      return true;
    }
  }
  return false;
}

/**
 * Normalize a file path: forward slashes, resolve '..' and '.' segments.
 */
function normalizePath(filePath: string): string {
  const parts = filePath.replace(/\\/g, '/').split('/');
  const resolved: string[] = [];
  for (const seg of parts) {
    if (seg === '..') resolved.pop();
    else if (seg !== '.' && seg !== '') resolved.push(seg);
  }
  return resolved.join('/');
}

/**
 * Match a file path against a single glob pattern.
 *
 * Supports:
 * - `**` matches any number of path segments (including zero)
 * - `*` matches any characters within a single path segment (no /)
 * - `?` matches any single character (not /)
 * - Literal characters match themselves
 * - Patterns without `/` match at any depth (like gitignore)
 *
 * @param filePath - Normalized file path (forward slashes)
 * @param pattern - Glob pattern to match against
 * @returns true if the path matches the pattern
 */
export function matchGlobPattern(filePath: string, pattern: string): boolean {
  // If the pattern contains no directory separator, it can match at any depth
  // (gitignore semantics: `*.ts` matches `src/foo.ts`, not just `foo.ts`)
  const effectivePattern = pattern.includes('/') ? pattern : `**/${pattern}`;

  // Convert glob pattern to regex
  const regexStr = globToRegex(effectivePattern);
  const regex = new RegExp(`^${regexStr}$`);
  return regex.test(filePath);
}

/**
 * Convert a glob pattern to a regex string.
 * Internal helper for matchGlobPattern.
 */
function globToRegex(pattern: string): string {
  let result = '';
  let i = 0;

  while (i < pattern.length) {
    const char = pattern[i];

    if (char === '*') {
      if (pattern[i + 1] === '*') {
        // ** — match any path segments
        if (pattern[i + 2] === '/') {
          // **/ — match zero or more directories
          result += '(?:.+/)?';
          i += 3;
        } else if (i + 2 >= pattern.length) {
          // ** at end — match everything
          result += '.*';
          i += 2;
        } else {
          // ** followed by something else
          result += '.*';
          i += 2;
        }
      } else {
        // * — match within a single path segment (no /)
        result += '[^/]*';
        i += 1;
      }
    } else if (char === '?') {
      result += '[^/]';
      i += 1;
    } else if (char === '.') {
      result += '\\.';
      i += 1;
    } else if (char === '\\') {
      result += '\\\\';
      i += 1;
    } else if (char === '(' || char === ')' || char === '+' || char === '^' || char === '$' || char === '|' || char === '{' || char === '}' || char === '[' || char === ']') {
      // Escape regex special chars
      result += '\\' + char;
      i += 1;
    } else {
      result += char;
      i += 1;
    }
  }

  return result;
}
